name: build and test feature branch

on:
  pull_request:
    branches: [ develop ]
    types: [opened, reopened ]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}
            
            - name: pull and checkout git repository
              run: |
                echo "pull and checkout git repository"
            
            - name: setup java 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: cache maven dependecies
              uses: actions/cache@v2
              with:
                path: ~/.m2/respository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                 ${{ runner.os }}-maven-
                 
            
            - name: build with maven
              run: |
                mvn clean test package
                echo "build with maven"




