name: build and test feature branch

on:
  pull_request:
    branches: [ develop ]
    types: [opened, reopened ]
    
jobs:
    build-feature:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}
            
            - name: pull and checkout git repository
              run: |
                echo "pull and checkout git repository"
            
            - name: setup java 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: cache maven dependecies
              uses: actions/cache@v2
              with:
                path: ~/.m2/respository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                 ${{ runner.os }}-maven-
                 
            
            - name: build with maven
              run: |
                mvn clean test package
                echo "build with maven"

    marge-feature-into-develop:
      runs-on: ubuntu-latest
      needs: build-feature

      if: ${{ success() }}
      permissions:
        contents: write
        pull-requests: write
      steps:

        - uses: actions/checkout@v3
          with:
            ref: ${{ github.base_ref }}
            fetch-depth: 0
        

        - name: Merge to development branch
          if: ${{ success() }}
          run: |
            git config --global user.email "cuddlelove709@gmail.com"
            git config --global user.name "notcuddle"
            git merge --no-ff --verbose origin/${{github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"
        
        - name: Push changes after merge
          if: ${{ success() }}
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.base_ref }}









